# Assembles dependencies from a classpath generated by clojure -Spath
#
# Usage: ./assemble.sh $(clojure -R:dev -Spath)

classpath=$1

# Clean output dir
mkdir -p target/classes
rm -rf target/classes/*

for path in ${classpath//:/ }; do
  if [[ -d $path ]]; then
      # Copy our source paths
      echo "Copying $path"
      cp -R $path/* target/classes/
  elif [[ -f $path && $path == *.jar ]]; then
      # Unpack jars, never overwriting (to retain classpath precedence)
      # Also exclude some extensions that will cause issues bundling signed jars
      echo "Unpacking $path"
      unzip -n -qq $path -x META-INF/*.SF META-INF/*.RSA META-INF/*.DSA -d target/classes > /dev/null 2>&1
  else
      echo "Ignoring $path"
  fi
done
